checkpoints:
  checkpoint_interval: 4000
  checkpoints_path: /leonardo_scratch/fast/EUHPC_D18_005/david/chess-bot-3000/nanotron/checkpoints/smollm3-100m-chess
  checkpoints_path_is_shared_file_system: true  # Shared filesystem on HPC
  load_lr_scheduler: true
  load_optimizer: true
  resume_checkpoint_path: null
  save_final_state: true
  save_initial_state: false

data_stages:
- data:
    dataset:
      dataset_overwrite_cache: false
      dataset_processing_num_proc_per_process: 8
      hf_dataset_config_name: null
      hf_dataset_or_datasets: /leonardo_scratch/large/userexternal/dhauser0/lichess/lichess_data/data_processed/year=2024/month=01
      hf_dataset_splits: train
      text_column_name: movetext_uci
    num_loading_workers: 6
    seed: 42
  name: stable
  sequence_length: 256
  start_training_step: 1

general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: chess-bot-3000
  run: 100m-jan24
  seed: 42
  step: null

logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info

model:
  ddp_bucket_cap_mb: 50
  dtype: bfloat16
  init_method:
    std: 0.02
  make_vocab_size_divisible_by: 1
  model_config:
    _attn_implementation: flash_attention_2
    _fused_rms_norm: true
    _fused_rotary_emb: true
    _use_doc_masking: true
    _use_qkv_packed: true
    attention_bias: false
    bos_token_id: 4613
    eos_token_id: 4614
    flex_attention_mask: null
    hidden_act: silu
    hidden_size: 768
    initializer_range: 0.02
    intermediate_size: 3072
    is_qwen2_config: true
    max_position_embeddings: 256
    moe_config: null
    num_attention_heads: 8
    num_hidden_layers: 12
    num_key_value_heads: 2
    pad_token_id: 1
    pretraining_tp: 1
    rms_norm_eps: 1.0e-06
    rope_interleaved: false
    rope_scaling: null
    rope_theta: 50000.0
    sliding_window_size: null
    tie_word_embeddings: true
    use_cache: true
    vocab_size: 4687
    z_loss_coefficient: 1.0e-05
    z_loss_enabled: false
    no_rope_layer: 1

optimizer:
  accumulate_grad_in_fp32: false
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0006          # Higher LR for smaller model
    lr_decay_starting_step: null
    lr_decay_steps: 25080          # ~95% of training
    lr_decay_style: cosine
    lr_warmup_steps: 520          # ~2% warmup
    lr_warmup_style: linear
    min_decay_lr: 6.0e-05          # 10% of peak LR
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.1
  weight_decay_exclude_named_params:
  - .*token_embedding.*
  zero_stage: 1

parallelism:
  context_parallel_size: 1
  dp: 4                            # Data parallel across 4 GPUs
  expert_parallel_size: 1
  moe_layer_recompute: false
  pp: 1                            # No pipeline parallelism needed for 100M
  pp_engine: 1f1b
  recompute_layer: false
  tp: 1                            # No tensor parallelism needed for 100M
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
  tp_recompute_allgather: true

profiler: null

tokenizer:
  tokenizer_max_length: 256
  tokenizer_name_or_path: ../tokenizer/uci_tokenizer_with_special_tokens
  tokenizer_revision: null

metrics_logging:
  log_level: 1
  log_detail_interval: 200

tokens:
  batch_accumulation_per_replica: 4    # Effective batch = num GPUs × micro × 8 accum = 1024
  limit_test_batches: 0
  limit_val_batches: 50
  micro_batch_size: 64                 # Per GPU, adjust based on VRAM
  sequence_length: 256
  train_steps: 26400                  # Adjust based on your data
  val_check_interval: 1000

lighteval: null

s3_upload: null