checkpoints:
  checkpoint_interval: 1000
  checkpoints_path: checkpoints
  checkpoints_path_is_shared_file_system: false
  load_lr_scheduler: true
  load_optimizer: true
  resume_checkpoint_path: null
  save_final_state: true
  save_initial_state: false

# data_stages:
# - data:
#     dataset:
#       dataset_overwrite_cache: false
#       dataset_processing_num_proc_per_process: 1
#       hf_dataset_config_name: null
#       hf_dataset_or_datasets: nampdn-ai/tiny-textbooks
#       hf_dataset_splits: train
#       text_column_name: text
#     num_loading_workers: 1
#     seed: 42
#   name: Stable Training Stage
#   start_training_step: 1

data_stages:
- data:
    dataset:
      dataset_overwrite_cache: false
      dataset_processing_num_proc_per_process: 1
      hf_dataset_config_name: null
      hf_dataset_or_datasets: ../data/lichess_data/data_processed
      hf_dataset_splits: train
      text_column_name: movetext_uci
    num_loading_workers: 1
    seed: 42
  name: Stable Training Stage
  sequence_length: 512
  start_training_step: 1

general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: smollm3-tiny-local
  run: tiny_smollm3_local_test
  seed: 42
  step: null

logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info

model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.02
  make_vocab_size_divisible_by: 1
  model_config:
    _attn_implementation: flash_attention_2
    _fused_rms_norm: true
    _fused_rotary_emb: true
    _use_doc_masking: true
    _use_qkv_packed: true
    attention_bias: false
    bos_token_id: 4613
    eos_token_id: 4614
    flex_attention_mask: null
    hidden_act: silu
    hidden_size: 256          # Much smaller than 2048
    initializer_range: 0.02
    intermediate_size: 1024   # Much smaller than 11008
    is_qwen2_config: true
    max_position_embeddings: 512  # Smaller context
    moe_config: null
    num_attention_heads: 8    # Reduced from 16
    num_hidden_layers: 4      # Much fewer than 36
    num_key_value_heads: 2    # Reduced from 4
    pad_token_id: 4098
    pretraining_tp: 1
    rms_norm_eps: 1.0e-06
    rope_interleaved: false
    rope_scaling: null
    rope_theta: 50000.0
    sliding_window_size: null
    tie_word_embeddings: true
    use_cache: true
    vocab_size: 4687
    z_loss_coefficient: 1.0e-05
    z_loss_enabled: false
    no_rope_layer: 1          # Reduced from 4

optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0003
    lr_decay_starting_step: null
    lr_decay_steps: 13
    lr_decay_style: cosine
    lr_warmup_steps: 2
    lr_warmup_style: linear
    min_decay_lr: 1.0e-05
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.1
  weight_decay_exclude_named_params:
  - .*token_embedding.*
  zero_stage: 0

parallelism:
  context_parallel_size: 1
  dp: 1
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  recompute_layer: false
  tp: 1
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
  tp_recompute_allgather: true

profiler: null

tokenizer:
  tokenizer_max_length: 512
  tokenizer_name_or_path: ../tokenizer/uci_tokenizer_with_special_tokens
  tokenizer_revision: null

metrics_logging: null

tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 10       # Small validation set
  micro_batch_size: 2
  sequence_length: 512        # Shorter sequences
  train_steps: 1000             # Just for quick testing
  val_check_interval: 10

lighteval: null

s3_upload: null